# Generated by Django 5.2.8 on 2025-11-07 20:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='academic_year',
        ),
        migrations.AlterField(
            model_name='class',
            name='academic_year',
            field=models.IntegerField(help_text='Academic year (e.g., 2025)', validators=[django.core.validators.MinValueValidator(2020)]),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='term',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_class',
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_class', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['grade', 'section'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.RenameField(
            model_name='class',
            old_name='grade_level',
            new_name='grade',
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('grade', 'section', 'academic_year')},
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='administrator',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='class',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
