# Generated by Django 5.2.8 on 2025-11-07 20:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_term_academic_year_alter_class_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='administrator',
            name='profile_color',
            field=models.CharField(choices=[('emerald', 'Emerald'), ('blue', 'Blue'), ('purple', 'Purple'), ('rose', 'Rose'), ('amber', 'Amber')], default='emerald', max_length=20),
        ),
        migrations.AddField(
            model_name='administrator',
            name='qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='administrator',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='administrator',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='TeacherAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Assignment History',
                'verbose_name_plural': 'Teacher Assignment Histories',
                'ordering': ['-start_date'],
            },
        ),
    ]
