# Generated by Django 5.2.8 on 2025-11-08 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_academicterm_student_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PROMOTION', 'End of Year Promotion'), ('CLASS_TRANSFER', 'Class Transfer')], max_length=15)),
                ('from_academic_year', models.IntegerField()),
                ('to_academic_year', models.IntegerField()),
                ('execution_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_students', models.IntegerField(default=0)),
                ('successful_moves', models.IntegerField(default=0)),
                ('failed_moves', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-execution_date'],
                'indexes': [models.Index(fields=['execution_date'], name='core_bulkmo_executi_2f7b77_idx'), models.Index(fields=['movement_type'], name='core_bulkmo_movemen_7e8dbb_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PROMOTION', 'Promotion'), ('DEMOTION', 'Demotion'), ('TRANSFER', 'Transfer'), ('GRADUATION', 'Graduation')], max_length=10)),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, null=True)),
                ('previous_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preserved_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_bulk_operation', models.BooleanField(default=False)),
                ('bulk_operation_id', models.CharField(blank=True, max_length=50, null=True)),
                ('from_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_departures', to='core.class')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.student')),
                ('to_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_arrivals', to='core.class')),
            ],
            options={
                'ordering': ['-movement_date'],
                'indexes': [models.Index(fields=['movement_date'], name='core_studen_movemen_1ac91e_idx'), models.Index(fields=['movement_type'], name='core_studen_movemen_94a091_idx'), models.Index(fields=['bulk_operation_id'], name='core_studen_bulk_op_59c25c_idx')],
            },
        ),
    ]
