# Generated by Django 5.2.8 on 2025-11-08 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='core.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.academicterm')),
            ],
            options={
                'ordering': ['-term__academic_year', '-term__term'],
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='TermFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.academicterm')),
            ],
            options={
                'ordering': ['-term__academic_year', '-term__term'],
                'unique_together': {('term',)},
            },
        ),
    ]
