# Generated by Django 5.2.8 on 2025-11-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('EXPELLED', 'Expelled')], default='ENROLLED', max_length=10),
        ),
    ]
