# Generated by Django 5.2.8 on 2025-11-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Your School Name', max_length=255, unique=True)),
                ('school_motto', models.CharField(blank=True, default='Quality Education for All', max_length=500)),
                ('school_code', models.CharField(blank=True, default='SCH001', max_length=50, unique=True)),
                ('principal_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('school_type', models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('HIGHER_SECONDARY', 'Higher Secondary School'), ('COMBINED', 'Combined School')], default='COMBINED', max_length=50)),
                ('board_affiliation', models.CharField(blank=True, max_length=200)),
                ('logo_url', models.URLField(blank=True)),
                ('header_color', models.CharField(default='#1e40af', help_text='Header background color (hex)', max_length=7)),
                ('accent_color', models.CharField(default='#0891b2', help_text='Accent color (hex)', max_length=7)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('working_days_per_week', models.IntegerField(choices=[(5, '5 Days'), (6, '6 Days')], default=6)),
                ('enable_online_payments', models.BooleanField(default=False)),
                ('payment_gateway', models.CharField(choices=[('NONE', 'None'), ('STRIPE', 'Stripe'), ('RAZORPAY', 'Razorpay'), ('PAYPAL', 'PayPal')], default='NONE', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Details',
                'verbose_name_plural': 'School Details',
            },
        ),
    ]
