# Generated by Django 5.2.8 on 2025-11-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_schooldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
