# Generated by Django 5.2.8 on 2025-11-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_academicterm_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
