# Generated by Django 5.2.8 on 2025-11-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_academicyear_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Graduated with all arrears paid - can be deleted'),
        ),
    ]
