# Generated by Django 5.2.8 on 2025-11-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_student_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when student was deleted', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_reason',
            field=models.CharField(blank=True, help_text='Reason for deletion', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag - financial records preserved for audit'),
        ),
    ]
