# Generated by Django 5.2.8 on 2025-11-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_student_deleted_at_student_deleted_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termfee',
            name='due_date',
        ),
    ]
