# Generated by Django 5.2.8 on 2025-12-06 20:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_termfee_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade7Statistics',
            fields=[
                ('academic_year', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2099)])),
                ('total_students', models.IntegerField(default=0)),
                ('students_sat_exams', models.IntegerField(default=0)),
                ('pass_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_aggregate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('top_aggregate', models.IntegerField(blank=True, null=True)),
                ('bottom_aggregate', models.IntegerField(blank=True, null=True)),
                ('english_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mathematics_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('science_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('social_studies_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('language_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('agriculture_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade 7 Statistics',
                'verbose_name_plural': 'Grade 7 Statistics',
                'ordering': ['-academic_year'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='alumni_date',
            field=models.DateTimeField(blank=True, help_text='When student became alumni (immediately upon full fee payment in Grade 7)', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('ACTIVE', 'Active'), ('ALUMNI', 'Alumni'), ('GRADUATED', 'Graduated'), ('EXPELLED', 'Expelled')], default='ENROLLED', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentmovement',
            name='moved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmovement',
            name='to_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_arrivals', to='core.class'),
        ),
        migrations.CreateModel(
            name='ZimsecResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2099)])),
                ('english_units', models.IntegerField(blank=True, help_text='1-5=Pass, 6-9=Fail', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('mathematics_units', models.IntegerField(blank=True, help_text='1-5=Pass, 6-9=Fail', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('science_units', models.IntegerField(blank=True, help_text='1-5=Pass, 6-9=Fail', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('social_studies_units', models.IntegerField(blank=True, help_text='1-5=Pass, 6-9=Fail', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('indigenous_language_units', models.IntegerField(blank=True, help_text='1-5=Pass, 6-9=Fail', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('agriculture_units', models.IntegerField(blank=True, help_text='1-5=Pass, 6-9=Fail', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('total_aggregate', models.IntegerField(blank=True, null=True)),
                ('overall_status', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=10, null=True)),
                ('exam_center', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='zimsec_results', to='core.student')),
            ],
            options={
                'verbose_name': 'ZIMSEC Result',
                'verbose_name_plural': 'ZIMSEC Results',
                'ordering': ['-academic_year', 'student__surname'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
