# Generated by Django 5.2.8 on 2025-12-07 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_grade7statistics_student_alumni_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Description of allocation action taken', max_length=200)),
                ('remaining_payment', models.DecimalField(decimal_places=2, help_text='Payment amount remaining after this action', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_logs', to='core.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_logs', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of credit available', max_digits=10)),
                ('source', models.CharField(choices=[('OVERPAYMENT', 'From overpayment'), ('SCHOLARSHIP', 'Scholarship/waiver'), ('ADJUSTMENT', 'Administrative adjustment'), ('GOODWILL', 'Goodwill credit')], default='OVERPAYMENT', max_length=50)),
                ('applied_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount that has been applied/used from this credit', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_payment', models.ForeignKey(blank=True, help_text='The payment that generated this credit (if from overpayment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_credits', to='core.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text='Amount allocated to this term or held as credit', max_digits=10)),
                ('allocation_type', models.CharField(choices=[('TERM_PAYMENT', 'Payment for specific term'), ('ARREARS_CLEARANCE', 'Clearing arrears from previous term'), ('CREDIT', 'Excess payment held as credit')], default='TERM_PAYMENT', max_length=20)),
                ('priority_order', models.IntegerField(help_text='Order in which allocations are applied (lower = first). Arrears cleared first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='core.student')),
                ('term', models.ForeignKey(blank=True, help_text='The term this allocation applies to. NULL for credit balances.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.academicterm')),
            ],
            options={
                'ordering': ['payment', 'priority_order'],
                'unique_together': {('payment', 'term', 'allocation_type')},
            },
        ),
    ]
