# Generated by Django 5.2.8 on 2025-12-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_paymentallocationlog_studentcredit_paymentallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbalance',
            name='previous_arrears',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Balance from previous term (positive=owe, negative=credit)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentbalance',
            name='term_fee',
            field=models.DecimalField(decimal_places=2, help_text='Original term fee charged', max_digits=10),
        ),
    ]
