# Generated by Django 5.2.8 on 2025-12-07 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_studentbalance_previous_arrears_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTermHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(help_text='e.g., 2027 for academic year 2027')),
                ('attendance_status', models.CharField(choices=[('PRESENT', 'Present - Attended and wrote exams'), ('ABSENT', 'Absent - Did not attend'), ('DROPPED', 'Dropped - Left during term'), ('TRANSFERRED', 'Transferred - Moved to another school')], default='PRESENT', help_text='Was the student present/absent/dropped during this term?', max_length=20)),
                ('exam_eligibility', models.CharField(choices=[('ELIGIBLE', 'Eligible - Attended, can sit exams'), ('NOT_ELIGIBLE', 'Not Eligible - Missed classes/requirements'), ('PENDING', 'Pending - Awaiting determination')], default='PENDING', help_text='Is the student eligible to sit for exams?', max_length=20)),
                ('zimsec_eligible', models.BooleanField(default=False, help_text='For Grade 7 Term 3: Did student sit ZIMSEC exams?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='core.academicterm')),
                ('class_enrolled', models.ForeignKey(help_text='The class student was in during this term', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_enrollments', to='core.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_history', to='core.student')),
            ],
            options={
                'verbose_name': 'Student Term History',
                'verbose_name_plural': 'Student Term Histories',
                'ordering': ['-academic_year', '-academic_term__term', 'student__surname'],
                'indexes': [models.Index(fields=['academic_year', 'academic_term'], name='core_studen_academi_c51909_idx'), models.Index(fields=['student', 'academic_year'], name='core_studen_student_a11103_idx'), models.Index(fields=['class_enrolled', 'academic_year'], name='core_studen_class_e_018e2d_idx')],
                'unique_together': {('student', 'academic_year', 'academic_term')},
            },
        ),
    ]
