# Generated by Django 5.2.8 on 2025-12-10 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_studenttermhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrearsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('TUITION', 'Tuition Fees'), ('MISC_FEES', 'Miscellaneous Fees'), ('UNIFORM', 'Uniform & Books'), ('ACTIVITIES', 'School Activities'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('affects_promotion', models.BooleanField(default=False, help_text='Whether unpaid arrears in this category prevent promotion/graduation')),
            ],
            options={
                'verbose_name_plural': 'Arrears Categories',
            },
        ),
        migrations.CreateModel(
            name='ArrearsImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft - In Progress'), ('VALIDATING', 'Validating Data'), ('READY', 'Ready for Import'), ('IMPORTED', 'Successfully Imported'), ('FAILED', 'Import Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('import_method', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('BULK_UPLOAD', 'Bulk Upload (Excel/CSV)'), ('COPY_PREVIOUS', 'Copy from Previous System')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('total_students_targeted', models.IntegerField(default=0)),
                ('students_with_arrears', models.IntegerField(default=0)),
                ('total_arrears_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upload_file', models.FileField(blank=True, help_text='Excel or CSV file for bulk import', null=True, upload_to='arrears_imports/')),
                ('processing_notes', models.TextField(blank=True, help_text='Notes about validation or processing')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrears_batches_created', to=settings.AUTH_USER_MODEL)),
                ('starting_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.academicterm')),
            ],
            options={
                'verbose_name': 'Arrears Import Batch',
                'verbose_name_plural': 'Arrears Import Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentArrearsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tuition_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('misc_fees_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_imported', models.DateTimeField(auto_now_add=True)),
                ('is_applied_to_balance', models.BooleanField(default=False, help_text='Whether arrears have been applied to student balance')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('is_paid_off', models.BooleanField(default=False)),
                ('paid_off_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('applied_to_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicterm')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.arrearsimportbatch')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrears_record', to='core.student')),
            ],
            options={
                'verbose_name': 'Student Arrears Record',
                'verbose_name_plural': 'Student Arrears Records',
            },
        ),
        migrations.CreateModel(
            name='ArrearsImportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrears_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arrears_description', models.CharField(blank=True, help_text='e.g., "2026 unpaid fees" or "2025-2026 cumulative"', max_length=255)),
                ('date_incurred', models.DateField(blank=True, help_text='When the arrears originated', null=True)),
                ('supporting_document', models.FileField(blank=True, help_text='PDF or image of supporting document', null=True, upload_to='arrears_documents/')),
                ('verified_amount', models.DecimalField(decimal_places=2, default=0, help_text='Verified amount after confirmation', max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Any validation or import errors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.arrearsimportbatch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrears_entries_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_arrears_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__surname', 'student__first_name'],
                'unique_together': {('batch', 'student')},
            },
        ),
    ]
