# Generated by Django 5.2.8 on 2025-12-12 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_arrearscategory_arrearsimportbatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbalance',
            name='term_fee',
        ),
        migrations.AddField(
            model_name='studentbalance',
            name='term_fee_record',
            field=models.ForeignKey(blank=True, help_text='Link to the term fee configuration', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.termfee'),
        ),
    ]
