# Generated by Django 5.2.8 on 2025-12-12 07:50

from django.db import migrations


def populate_term_fee_record(apps, schema_editor):
    """Populate term_fee_record by matching StudentBalance to TermFee by term"""
    StudentBalance = apps.get_model('core', 'StudentBalance')
    TermFee = apps.get_model('core', 'TermFee')
    
    # For each StudentBalance, find its corresponding TermFee by term_id
    for balance in StudentBalance.objects.all():
        try:
            term_fee = TermFee.objects.get(term_id=balance.term_id)
            balance.term_fee_record = term_fee
            balance.save()
        except TermFee.DoesNotExist:
            # If no TermFee exists for this term, we have a data inconsistency
            print(f"Warning: No TermFee for term {balance.term_id}")


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear term_fee_record"""
    StudentBalance = apps.get_model('core', 'StudentBalance')
    StudentBalance.objects.all().update(term_fee_record=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_studentbalance_term_fee_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_term_fee_record, reverse_populate),
    ]
