# Generated by Django 5.2.8 on 2025-12-12 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_populate_term_fee_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbalance',
            name='term_fee_record',
            field=models.ForeignKey(help_text='Link to the term fee configuration', on_delete=django.db.models.deletion.PROTECT, to='core.termfee'),
        ),
    ]
