# Generated by Django 5.2.8 on 2025-12-19 22:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_arrears_vault_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='arrearsvault',
            new_name='arrears_vau_student_7d1f5d_idx',
            old_name='arrears_vau_student_idx',
        ),
        migrations.RenameIndex(
            model_name='arrearsvault',
            new_name='arrears_vau_graduat_f9e7b9_idx',
            old_name='arrears_vau_grad_year_idx',
        ),
        migrations.RenameIndex(
            model_name='arrearsvault',
            new_name='arrears_vau_status_29a005_idx',
            old_name='arrears_vau_status_idx',
        ),
        migrations.RenameIndex(
            model_name='arrearsvault',
            new_name='arrears_vau_fixed_b_0eb215_idx',
            old_name='arrears_vau_balance_idx',
        ),
        migrations.AlterField(
            model_name='arrearsvault',
            name='fixed_balance',
            field=models.DecimalField(decimal_places=2, help_text='Fixed outstanding amount - NEVER CHANGES until paid', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
