# Generated by Django 5.2.8 on 2026-01-03 12:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_add_ecd_separate_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.CharField(choices=[('ECD', 'ECD (Early Childhood Development)'), (1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7')], max_length=4),
        ),
        migrations.CreateModel(
            name='ECDClassProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=30, help_text='Maximum pupils in this ECD class')),
                ('premium', models.BooleanField(default=False, help_text='Marks this ECD class as a premium offering')),
                ('meal_plan_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('nappies_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('materials_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cls', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecd_profile', to='core.class')),
            ],
        ),
        migrations.CreateModel(
            name='ECDClassFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecd_fees', to='core.class')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicterm')),
            ],
            options={
                'unique_together': {('cls', 'term')},
            },
        ),
    ]
